services:
  test-fileserver:
    image: nginx:stable-alpine3.17-slim
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./test-fileserver/data:/srv
      - ./test-fileserver/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fact-extractor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  fact-extractor-backend:
    image: fact-extractor-backend:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app
    networks:
      - fact-extractor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  fact-extractor-frontend:
    image: fact-extractor-frontend:latest
    command: npm run start:dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - fact-extractor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  fact-extractor:
