services:
  test-fileserver:
    image: nginx:stable-alpine3.17-slim
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./test-fileserver/data:/srv
      - ./test-fileserver/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - llm-log-parser
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  llm-log-parser-backend:
    image: llm-log-parser-backend:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app
    networks:
      - llm-log-parser
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  llm-log-parser-frontend:
    image: llm-log-parser-frontend:latest
    command: ng serve --host 0.0.0.0 --configuration development
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - llm-log-parser
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  llm-log-parser:
